#!/usr/bin/env bash
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║  OmniScript - Docker Adapter                                               ║
# ║  Deploy applications using Docker and docker-compose                       ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

[[ -n "${_OS_ADAPTER_DOCKER_LOADED:-}" ]] && return 0
readonly _OS_ADAPTER_DOCKER_LOADED=1

# Load base adapter
source "${OS_ADAPTERS_DIR}/base.sh"

ADAPTER_NAME="docker"
ADAPTER_TYPE="container"

# Check Docker availability
docker_is_available() {
    command -v docker &>/dev/null && docker info &>/dev/null
}

# Get latest stable tag from Docker Hub
docker_get_latest_tag() {
    local image="$1"
    local repo="${image%%:*}"
    
    # Try to get tags from Docker Hub API
    local tags_url="https://hub.docker.com/v2/repositories/library/${repo}/tags?page_size=100"
    [[ "$repo" == *"/"* ]] && tags_url="https://hub.docker.com/v2/repositories/${repo}/tags?page_size=100"
    
    local tags
    tags=$(curl -sSL "$tags_url" 2>/dev/null | grep -oP '"name":"\K[^"]+' | head -20)
    
    # Find latest stable (not latest, not rc, not alpha, not beta)
    local stable_tag=""
    while IFS= read -r tag; do
        if [[ "$tag" =~ ^[0-9]+\.[0-9]+ ]] && [[ ! "$tag" =~ (rc|alpha|beta|dev|test) ]]; then
            stable_tag="$tag"
            break
        fi
    done <<< "$tags"
    
    echo "${stable_tag:-latest}"
}

# Generate docker-compose.yml
docker_generate_compose() {
    local app_name="${APP_NAME:-app}"
    local image="${DOCKER_IMAGE:-}"
    local tag="${DOCKER_TAG:-}"
    
    # Get latest tag if not specified
    [[ -z "$tag" ]] && tag=$(docker_get_latest_tag "$image")
    
    local compose_dir
    compose_dir=$(os_ensure_app_data_dir "$app_name")
    local compose_file="${compose_dir}/docker-compose.yml"
    
    os_log_info "Generating docker-compose.yml..."
    
    {
        echo "# Generated by OmniScript"
        echo "# $(date -Iseconds)"
        echo ""
        echo "services:"
        echo "  ${app_name}:"
        echo "    image: ${image}:${tag}"
        echo "    container_name: os-${app_name}"
        echo "    restart: unless-stopped"
        
        # Environment variables
        if [[ -n "${ENVIRONMENT[*]:-}" ]]; then
            echo "    environment:"
            for env in "${ENVIRONMENT[@]}"; do
                # Expand variables
                local expanded
                expanded=$(eval echo "$env")
                echo "      - ${expanded}"
            done
        fi
        
        # Ports
        if [[ -n "${PORTS[*]:-}" ]]; then
            echo "    ports:"
            for port in "${PORTS[@]}"; do
                echo "      - \"${port}:${port}\""
            done
        fi
        
        # Volumes
        if [[ -n "${VOLUMES[*]:-}" ]]; then
            echo "    volumes:"
            for vol in "${VOLUMES[@]}"; do
                echo "      - ${vol}"
            done
        fi
        
        # Labels
        echo "    labels:"
        echo "      - omniscript.managed=true"
        echo "      - omniscript.app=${app_name}"
        
    } > "$compose_file"
    
    os_log_success "Generated: $compose_file"
    echo "$compose_file"
}

# Install application
adapter_install() {
    if ! docker_is_available; then
        os_log_error "Docker is not available"
        return 1
    fi
    
    local app_name="${APP_NAME:-}"
    
    os_log_step 1 4 "Generating compose file..."
    local compose_file
    compose_file=$(docker_generate_compose)
    
    os_log_step 2 4 "Pulling image..."
    local image="${DOCKER_IMAGE:-}"
    local tag
    tag=$(docker_get_latest_tag "$image")
    
    os_spinner_start "Pulling ${image}:${tag}..."
    docker pull "${image}:${tag}" &>/dev/null
    os_spinner_stop
    os_log_success "Image pulled: ${image}:${tag}"
    
    os_log_step 3 4 "Starting container..."
    local compose_dir
    compose_dir=$(dirname "$compose_file")
    docker compose -f "$compose_file" up -d
    
    os_log_step 4 4 "Verifying..."
    sleep 2
    
    local container_id
    container_id=$(docker compose -f "$compose_file" ps -q 2>/dev/null | head -1)
    
    if [[ -n "$container_id" ]]; then
        os_track_installation "$app_name" "docker" "$container_id"
        os_log_success "Container started: $container_id"
    else
        os_log_error "Failed to start container"
        return 1
    fi
}

# Start application
adapter_start() {
    local app_name="${APP_NAME:-}"
    local compose_file
    compose_file="$(os_get_app_data_dir "$app_name")/docker-compose.yml"
    
    if [[ -f "$compose_file" ]]; then
        docker compose -f "$compose_file" start
        os_log_success "Started $app_name"
    else
        docker start "os-${app_name}" 2>/dev/null || {
            os_log_error "Could not start $app_name"
            return 1
        }
    fi
}

# Stop application
adapter_stop() {
    local app_name="${APP_NAME:-}"
    local compose_file
    compose_file="$(os_get_app_data_dir "$app_name")/docker-compose.yml"
    
    if [[ -f "$compose_file" ]]; then
        docker compose -f "$compose_file" stop
    else
        docker stop "os-${app_name}" 2>/dev/null
    fi
    os_log_success "Stopped $app_name"
}

# Get status
adapter_status() {
    local app_name="${APP_NAME:-}"
    docker ps -a --filter "name=os-${app_name}" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
}

# View logs
adapter_logs() {
    local app_name="${APP_NAME:-}"
    local lines="${1:-100}"
    docker logs --tail "$lines" -f "os-${app_name}"
}

# Backup
adapter_backup() {
    local app_name="${APP_NAME:-}"
    local backup_dir="${OS_CONFIG[BACKUP_DIR]:-/var/backups/omniscript}"
    local timestamp
    timestamp=$(date +%Y%m%d_%H%M%S)
    local backup_file="${backup_dir}/${app_name}_docker_${timestamp}.tar.gz"
    
    os_ensure_dir "$backup_dir"
    
    os_log_info "Backing up $app_name..."
    
    # Export container
    local container="os-${app_name}"
    docker export "$container" | gzip > "${backup_file%.tar.gz}_container.tar.gz"
    
    # Backup volumes
    local data_dir
    data_dir=$(os_get_app_data_dir "$app_name")
    if [[ -d "$data_dir" ]]; then
        tar -czf "$backup_file" -C "$(dirname "$data_dir")" "$(basename "$data_dir")"
    fi
    
    os_log_success "Backup created: $backup_file"
}

# Restore
adapter_restore() {
    local backup_file="$1"
    
    if [[ ! -f "$backup_file" ]]; then
        os_log_error "Backup file not found: $backup_file"
        return 1
    fi
    
    os_log_info "Restoring from $backup_file..."
    
    # Extract and restore
    local app_name
    app_name=$(basename "$backup_file" | sed 's/_docker_.*//')
    local data_dir
    data_dir=$(os_get_app_data_dir "$app_name")
    
    tar -xzf "$backup_file" -C "$(dirname "$data_dir")"
    
    # Restart with compose
    local compose_file="${data_dir}/docker-compose.yml"
    if [[ -f "$compose_file" ]]; then
        docker compose -f "$compose_file" up -d
    fi
    
    os_log_success "Restored $app_name"
}

# Update
adapter_update() {
    local app_name="${APP_NAME:-}"
    local compose_file
    compose_file="$(os_get_app_data_dir "$app_name")/docker-compose.yml"
    
    if [[ ! -f "$compose_file" ]]; then
        os_log_error "Compose file not found"
        return 1
    fi
    
    os_log_info "Updating $app_name..."
    
    # Pull new image
    docker compose -f "$compose_file" pull
    
    # Recreate container with new image
    docker compose -f "$compose_file" up -d --force-recreate
    
    os_log_success "Updated $app_name"
}

# Remove
adapter_remove() {
    local app_name="${APP_NAME:-}"
    local compose_file
    compose_file="$(os_get_app_data_dir "$app_name")/docker-compose.yml"
    
    if os_confirm "Remove $app_name and all its data?"; then
        if [[ -f "$compose_file" ]]; then
            docker compose -f "$compose_file" down -v
        else
            docker rm -f "os-${app_name}" 2>/dev/null
        fi
        
        # Remove data directory
        local data_dir
        data_dir=$(os_get_app_data_dir "$app_name")
        rm -rf "$data_dir"
        
        os_untrack_installation "$app_name"
        os_log_success "Removed $app_name"
    fi
}
