#!/usr/bin/env bash
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║  OmniScript - Podman Adapter                                               ║
# ║  Deploy applications using Podman (rootless containers)                    ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

[[ -n "${_OS_ADAPTER_PODMAN_LOADED:-}" ]] && return 0
readonly _OS_ADAPTER_PODMAN_LOADED=1

source "${OS_ADAPTERS_DIR}/base.sh"

ADAPTER_NAME="podman"
ADAPTER_TYPE="container"

podman_is_available() {
    command -v podman &>/dev/null
}

podman_get_latest_tag() {
    local image="$1"
    local repo="${image%%:*}"
    
    # Podman can query docker.io
    local tags
    tags=$(podman search --list-tags "docker.io/library/${repo}" --limit 20 2>/dev/null | awk 'NR>1 {print $2}' | head -20)
    
    local stable_tag=""
    while IFS= read -r tag; do
        if [[ "$tag" =~ ^[0-9]+\.[0-9]+ ]] && [[ ! "$tag" =~ (rc|alpha|beta|dev) ]]; then
            stable_tag="$tag"
            break
        fi
    done <<< "$tags"
    
    echo "${stable_tag:-latest}"
}

podman_generate_compose() {
    local app_name="${APP_NAME:-app}"
    local image="${PODMAN_IMAGE:-${DOCKER_IMAGE:-}}"
    local tag="${PODMAN_TAG:-}"
    
    [[ -z "$tag" ]] && tag=$(podman_get_latest_tag "$image")
    
    local compose_dir
    compose_dir=$(os_ensure_app_data_dir "$app_name")
    local compose_file="${compose_dir}/podman-compose.yml"
    
    {
        echo "# Generated by OmniScript for Podman"
        echo "version: '3'"
        echo ""
        echo "services:"
        echo "  ${app_name}:"
        echo "    image: ${image}:${tag}"
        echo "    container_name: os-${app_name}"
        echo "    restart: unless-stopped"
        
        if [[ -n "${ENVIRONMENT[*]:-}" ]]; then
            echo "    environment:"
            for env in "${ENVIRONMENT[@]}"; do
                echo "      - $(eval echo "$env")"
            done
        fi
        
        if [[ -n "${PORTS[*]:-}" ]]; then
            echo "    ports:"
            for port in "${PORTS[@]}"; do
                echo "      - \"${port}:${port}\""
            done
        fi
        
        if [[ -n "${VOLUMES[*]:-}" ]]; then
            echo "    volumes:"
            for vol in "${VOLUMES[@]}"; do
                echo "      - ${vol}"
            done
        fi
    } > "$compose_file"
    
    echo "$compose_file"
}

adapter_install() {
    if ! podman_is_available; then
        os_log_error "Podman is not available"
        return 1
    fi
    
    local app_name="${APP_NAME:-}"
    local image="${PODMAN_IMAGE:-${DOCKER_IMAGE:-}}"
    local tag
    tag=$(podman_get_latest_tag "$image")
    
    os_log_step 1 3 "Pulling image..."
    os_spinner_start "Pulling ${image}:${tag}..."
    podman pull "${image}:${tag}" &>/dev/null
    os_spinner_stop
    
    os_log_step 2 3 "Creating container..."
    
    local run_args=("--name" "os-${app_name}" "-d")
    
    for port in "${PORTS[@]:-}"; do
        run_args+=("-p" "${port}:${port}")
    done
    
    for env in "${ENVIRONMENT[@]:-}"; do
        run_args+=("-e" "$(eval echo "$env")")
    done
    
    for vol in "${VOLUMES[@]:-}"; do
        run_args+=("-v" "$vol")
    done
    
    run_args+=("${image}:${tag}")
    
    local container_id
    container_id=$(podman run "${run_args[@]}")
    
    os_log_step 3 3 "Verifying..."
    
    if [[ -n "$container_id" ]]; then
        os_track_installation "$app_name" "podman" "$container_id"
        os_log_success "Container started: ${container_id:0:12}"
    else
        os_log_error "Failed to start container"
        return 1
    fi
}

adapter_start() {
    podman start "os-${APP_NAME:-}" && os_log_success "Started ${APP_NAME:-}"
}

adapter_stop() {
    podman stop "os-${APP_NAME:-}" && os_log_success "Stopped ${APP_NAME:-}"
}

adapter_status() {
    podman ps -a --filter "name=os-${APP_NAME:-}" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
}

adapter_logs() {
    podman logs --tail "${1:-100}" -f "os-${APP_NAME:-}"
}

adapter_backup() {
    local app_name="${APP_NAME:-}"
    local backup_dir="${OS_CONFIG[BACKUP_DIR]:-/var/backups/omniscript}"
    local timestamp; timestamp=$(date +%Y%m%d_%H%M%S)
    local backup_file="${backup_dir}/${app_name}_podman_${timestamp}.tar"
    
    os_ensure_dir "$backup_dir"
    
    podman export "os-${app_name}" > "$backup_file"
    gzip "$backup_file"
    
    os_log_success "Backup: ${backup_file}.gz"
}

adapter_restore() {
    local backup_file="$1"
    os_log_info "Restoring from $backup_file..."
    
    local app_name; app_name=$(basename "$backup_file" | sed 's/_podman_.*//')
    gunzip -c "$backup_file" | podman import - "os-${app_name}-restored"
    
    os_log_success "Restored as os-${app_name}-restored"
}

adapter_update() {
    local app_name="${APP_NAME:-}"
    local image="${PODMAN_IMAGE:-${DOCKER_IMAGE:-}}"
    
    os_log_info "Updating $app_name..."
    
    # Get current config
    local old_container; old_container=$(podman inspect "os-${app_name}" --format json 2>/dev/null)
    
    # Pull new image
    podman pull "$image"
    
    # Stop and remove old
    podman stop "os-${app_name}" 2>/dev/null
    podman rm "os-${app_name}" 2>/dev/null
    
    # Recreate
    adapter_install
    
    os_log_success "Updated $app_name"
}

adapter_remove() {
    local app_name="${APP_NAME:-}"
    
    if os_confirm "Remove $app_name?"; then
        podman rm -f "os-${app_name}" 2>/dev/null
        os_untrack_installation "$app_name"
        os_log_success "Removed $app_name"
    fi
}
