#!/usr/bin/env bash
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║  OmniScript - Traefik Application Manifest                                 ║
# ║  Cloud-native reverse proxy and load balancer                              ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

APP_NAME="traefik"
APP_DESCRIPTION="Traefik - Cloud-native reverse proxy and load balancer"
APP_CATEGORY="proxy"
APP_WEBSITE="https://traefik.io"

# Images
DOCKER_IMAGE="traefik"
PODMAN_IMAGE="docker.io/library/traefik"
LXC_IMAGE="images:alpine/edge"

# Packages (for bare metal - requires manual config)
APT_PACKAGES=""
DNF_PACKAGES=""
APK_PACKAGES="traefik"

# Ports
PORTS=(80 443 8080)

# Volumes
VOLUMES=(
    "${OS_CONFIG_DIR}/data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    "${OS_CONFIG_DIR}/data/traefik/dynamic:/etc/traefik/dynamic:ro"
    "${OS_CONFIG_DIR}/data/traefik/acme:/etc/traefik/acme"
    "/var/run/docker.sock:/var/run/docker.sock:ro"
)

# Environment
ENVIRONMENT=()

# Configurable
CONFIGURABLE=(
    "DOMAIN:string:localhost:Primary domain"
    "ACME_EMAIL:string::Email for Let's Encrypt certificates"
    "DASHBOARD:bool:true:Enable Traefik dashboard"
    "DASHBOARD_AUTH:password::Dashboard password (auto-generated)"
)

pre_install() {
    os_log_info "Preparing Traefik installation..."
    
    os_ensure_dir "${OS_CONFIG_DIR}/data/traefik/dynamic"
    os_ensure_dir "${OS_CONFIG_DIR}/data/traefik/acme"
    
    # Generate dashboard password
    if [[ -z "${APP_DASHBOARD_AUTH:-}" ]]; then
        APP_DASHBOARD_AUTH=$(os_generate_password 24)
        export APP_DASHBOARD_AUTH
    fi
    
    # Create traefik.yml
    cat > "${OS_CONFIG_DIR}/data/traefik/traefik.yml" << EOF
# Traefik Configuration - Generated by OmniScript

api:
  dashboard: ${APP_DASHBOARD:-true}
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${APP_ACME_EMAIL:-admin@example.com}"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}
EOF

    # Create dynamic config
    cat > "${OS_CONFIG_DIR}/data/traefik/dynamic/dashboard.yml" << EOF
# Traefik Dashboard Configuration
http:
  routers:
    dashboard:
      rule: "Host(\`traefik.${APP_DOMAIN:-localhost}\`)"
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$(echo "$APP_DASHBOARD_AUTH" | htpasswd -nBi admin 2>/dev/null | tail -1 || echo 'admin:$2y$10$placeholder')"
EOF
}

post_install() {
    os_log_success "Traefik installed!"
    os_store_credential "traefik_dashboard" "http://localhost:8080/dashboard/"
    os_store_credential "traefik_user" "admin"
    os_store_credential "traefik_password" "$APP_DASHBOARD_AUTH"
}
